import 'package:get/get_navigation/get_navigation.dart';
import 'package:shaudan_b2b/res/localizations/app_strings.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          AppStrings.startMessage: 'Start your \nbusiness with us',
          AppStrings.retailer: 'Retailer',
          AppStrings.wholesaler: 'Wholesaler',
          AppStrings.home: 'Home',
          AppStrings.notify: 'Notify',
          AppStrings.cart: 'Cart',
          AppStrings.liked: 'Liked',
          AppStrings.account: 'Account',
          AppStrings.search: 'Search',
          AppStrings.searchHint: 'Search by product',
          AppStrings.login: 'Login',
          AppStrings.signUp: 'Sign Up',
          AppStrings.signUpAs: 'Sign Up As',
          AppStrings.forgotPassword: 'Forgot Password',
          AppStrings.email: 'Email',
          AppStrings.emailHint: 'Enter your email',
          AppStrings.password: 'Password',
          AppStrings.passwordHint: 'Enter your password',
          AppStrings.confirmPassword: 'Confirm Password',
          AppStrings.confirmPasswordHint: 'Enter your confirm password',
          AppStrings.name: 'Name',
          AppStrings.nameHint: 'Enter your name',
          AppStrings.storeName: 'Store Name',
          AppStrings.storeNameHint: 'Enter your store name',
          AppStrings.loginScreenTitle: 'Login',
          AppStrings.signUpScreenTitle: 'Sign Up',
          AppStrings.contact: 'Contact',
          AppStrings.orderHistory: 'Order History',
          AppStrings.reviews: 'Reviews',
          AppStrings.settings: 'Settings',
          AppStrings.logout: 'Logout',
          AppStrings.english: 'English',
          AppStrings.urdu: 'Urdu',
          AppStrings.pleaseEnter: 'Please enter',
          AppStrings.shouldbeAtleast6Characters:
              'should be atleast 6 characters',
          AppStrings.passwordAndConfirmPasswordShouldBeSame:
              'password and confirm password should be same',
          AppStrings.phone: 'Phone',
          AppStrings.phoneHint: 'Enter your phone',
          AppStrings.order: 'Order',
          AppStrings.dashboard: 'Dashboard',
          AppStrings.orderDetails: 'Order Details',
          AppStrings.orderStatus: 'Order Status',
          AppStrings.orderDate: 'Order Date',
          AppStrings.orderAmount: 'Order Amount',
          AppStrings.orderItems: 'Order Items',
          AppStrings.orderItem: 'Order Item',
          AppStrings.orderItemName: 'Order Item Name',
          AppStrings.orderItemQuantity: 'Order Item Quantity',
          AppStrings.orderItemPrice: 'Order Item Price',
          AppStrings.orderItemTotal: 'Order Item Total',
          AppStrings.addItems: 'Add Items',
          AppStrings.upload: 'Upload',
          AppStrings.uploadProduct: 'Upload Product',
          AppStrings.productDetails: 'Product Details',
          AppStrings.productName: 'Product Name',
          AppStrings.productNameHint: 'Enter your product name',
          AppStrings.productDescription: 'Product Description',
          AppStrings.productDescriptionHint: 'Enter your product description',
          AppStrings.productPrice: 'Product Price',
          AppStrings.productPriceHint: 'Enter your product price',
          AppStrings.productQuantity: 'Product Quantity',
          AppStrings.productQuantityHint: 'Enter your product quantity',
          AppStrings.productCategory: 'Product Category',
          AppStrings.productCategoryHint: 'Enter your product category',
          AppStrings.productSubCategory: 'Product Sub Category',
          AppStrings.productSubCategoryHint: 'Enter your product sub category',
          AppStrings.productBrand: 'Product Brand',
          AppStrings.productBrandHint: 'Enter your product brand',
        },
        'ur_PK': {
          AppStrings.startMessage: 'ہمارے ساتھ اپنا کاروبار شروع کریں',
          AppStrings.retailer: 'ریٹیلر',
          AppStrings.wholesaler: 'ھولسیلر',
          AppStrings.home: 'گھر',
          AppStrings.notify: 'اطلاع دیں',
          AppStrings.cart: 'ٹوکری',
          AppStrings.liked: 'پسندیدہ',
          AppStrings.account: 'اکاؤنٹ',
          AppStrings.search: 'تلاش کریں',
          AppStrings.searchHint: 'مصنوعات کے ذریعہ تلاش کریں',
          AppStrings.login: 'لاگ ان کریں',
          AppStrings.signUp: 'سائن اپ کریں',
          AppStrings.signUpAs: 'سائن اپ کریں',
          AppStrings.email: 'ای میل',
          AppStrings.emailHint: 'اپنا ای میل درج کریں',
          AppStrings.password: 'پاس ورڈ',
          AppStrings.passwordHint: 'اپنا پاس ورڈ درج کریں',
          AppStrings.confirmPassword: 'پاس ورڈ کی تصدیق کریں',
          AppStrings.confirmPasswordHint: 'اپنا پاس ورڈ کی تصدیق کریں',
          AppStrings.name: 'نام',
          AppStrings.nameHint: 'اپنا نام درج کریں',
          AppStrings.storeName: 'اسٹور کا نام',
          AppStrings.storeNameHint: 'اپنا اسٹور کا نام درج کریں',
          AppStrings.loginScreenTitle: 'لاگ ان کریں',
          AppStrings.signUpScreenTitle: 'سائن اپ کریں',
          AppStrings.contact: 'رابطہ کریں',
          AppStrings.orderHistory: 'آرڈر کی تاریخ',
          AppStrings.reviews: 'جائزے',
          AppStrings.settings: 'ترتیبات',
          AppStrings.logout: 'لاگ آؤٹ',
          AppStrings.english: 'انگریزی',
          AppStrings.urdu: 'اردو',
          AppStrings.pleaseEnter: 'درج کریں',
          AppStrings.shouldbeAtleast6Characters: 'کم از کم 6 حروف ہونے چاہئیں',
          AppStrings.passwordAndConfirmPasswordShouldBeSame:
              'پاس ورڈ اور تصدیقی پاس ورڈ ایک جیسے ہونے چاہئیں',
          AppStrings.phone: 'فون',
          AppStrings.phoneHint: 'اپنا فون درج کریں',
          AppStrings.order: 'آرڈر',
          AppStrings.dashboard: 'ڈیش بورڈ',
          AppStrings.orderDetails: 'آرڈر کی تفصیلات',
          AppStrings.orderStatus: 'آرڈر کی حیثیت',
          AppStrings.orderDate: 'آرڈر کی تاریخ',
          AppStrings.orderAmount: 'آرڈر کی رقم',
          AppStrings.orderItems: 'آرڈر آئٹمز',
          AppStrings.orderItem: 'آرڈر آئٹم',
          AppStrings.orderItemName: 'آرڈر آئٹم کا نام',
          AppStrings.orderItemQuantity: 'آرڈر آئٹم کی مقدار',
          AppStrings.orderItemPrice: 'آرڈر آئٹم کی قیمت',
          AppStrings.orderItemTotal: 'آرڈر آئٹم کل',
          AppStrings.addItems: 'آئٹمز شامل کریں',
          AppStrings.uploadProduct: 'پروڈکٹ اپ لوڈ کریں',
          AppStrings.productDetails: 'پروڈکٹ کی تفصیلات',
          AppStrings.productName: 'پروڈکٹ کا نام',
          AppStrings.productNameHint: 'اپنا پروڈکٹ کا نام درج کریں',
          AppStrings.productDescription: 'پروڈکٹ کی تفصیلات',
          AppStrings.productDescriptionHint: 'اپنی پروڈکٹ کی تفصیلات درج کریں',
          AppStrings.productPrice: 'پروڈکٹ کی قیمت',
          AppStrings.productPriceHint: 'اپنی پروڈکٹ کی قیمت درج کریں',
          AppStrings.productQuantity: 'پروڈکٹ کی مقدار',
          AppStrings.productQuantityHint: 'اپنی پروڈکٹ کی مقدار درج کریں',
          AppStrings.productCategory: 'پروڈکٹ کی قسم',
          AppStrings.productCategoryHint: 'اپنی پروڈکٹ کی قسم درج کریں',
          AppStrings.productSubCategory: 'پروڈکٹ کی ذیلی قسم',
          AppStrings.productSubCategoryHint: 'اپنی پروڈکٹ کی ذیلی قسم درج کریں',
          AppStrings.productBrand: 'پروڈکٹ کا برانڈ',
          AppStrings.productBrandHint: 'اپنی پروڈکٹ کا برانڈ درج کریں',
        },
      };
}
