// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCQlcw7Ekg41HXvROxFnutNDkqXdkFefdI',
//     appId: '1:381713326569:web:1e6ff796a9351407f2eb78',
//     messagingSenderId: '381713326569',
//     projectId: 'store-fd382',
//     authDomain: 'store-fd382.firebaseapp.com',
//     storageBucket: 'store-fd382.appspot.com',
//     measurementId: 'G-GTTMLLH5X1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBQwoXqIR_HOabR5i-D1zXERg2yhbZvumA',
//     appId: '1:381713326569:android:3f87d4355d19c496f2eb78',
//     messagingSenderId: '381713326569',
//     projectId: 'store-fd382',
//     storageBucket: 'store-fd382.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDP_IAQvycBxpTGWrtr6ibPXDf9M5uu4S0',
//     appId: '1:381713326569:ios:ca44277883a56037f2eb78',
//     messagingSenderId: '381713326569',
//     projectId: 'store-fd382',
//     storageBucket: 'store-fd382.appspot.com',
//     iosClientId: '381713326569-2imscd509od30id9o8t184ml13l41gql.apps.googleusercontent.com',
//     iosBundleId: 'com.example.shaudanB2b',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDP_IAQvycBxpTGWrtr6ibPXDf9M5uu4S0',
//     appId: '1:381713326569:ios:6e79e8952c911b58f2eb78',
//     messagingSenderId: '381713326569',
//     projectId: 'store-fd382',
//     storageBucket: 'store-fd382.appspot.com',
//     iosClientId: '381713326569-25k2lmcralnjgiihqe6n890vf1o7kbfi.apps.googleusercontent.com',
//     iosBundleId: 'com.example.shaudanB2b.RunnerTests',
//   );
// }
